version: '3'
services:
  tomcat:
    image: tomcat:9.0
    container_name: servlet-container
    ports:
      - "8080:8080"
    volumes:
      - ./target/TaskBazaar-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/TaskBazaar-1.0-SNAPSHOT.war
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: Test
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
